# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui5.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1130, 540))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_rev5_r2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_r2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_r2.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_r2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_r2.setObjectName("lineEdit_rev5_r2")
        self.gridLayout.addWidget(self.lineEdit_rev5_r2, 13, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 6)
        self.lineEdit_rev5_l3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_l3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_l3.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_l3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_l3.setObjectName("lineEdit_rev5_l3")
        self.gridLayout.addWidget(self.lineEdit_rev5_l3, 13, 6, 1, 1)
        self.label_rev8_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev8_2.sizePolicy().hasHeightForWidth())
        self.label_rev8_2.setSizePolicy(sizePolicy)
        self.label_rev8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev8_2.setObjectName("label_rev8_2")
        self.gridLayout.addWidget(self.label_rev8_2, 14, 0, 1, 1)
        self.label_rev11_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev11_2.sizePolicy().hasHeightForWidth())
        self.label_rev11_2.setSizePolicy(sizePolicy)
        self.label_rev11_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev11_2.setObjectName("label_rev11_2")
        self.gridLayout.addWidget(self.label_rev11_2, 15, 0, 1, 1)
        self.label_rev5_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev5_2.sizePolicy().hasHeightForWidth())
        self.label_rev5_2.setSizePolicy(sizePolicy)
        self.label_rev5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev5_2.setObjectName("label_rev5_2")
        self.gridLayout.addWidget(self.label_rev5_2, 13, 0, 1, 1)
        self.lineEdit_rev3_l2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_l2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_l2.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_l2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_l2.setObjectName("lineEdit_rev3_l2")
        self.gridLayout.addWidget(self.lineEdit_rev3_l2, 12, 5, 1, 1)
        self.label_rev3_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev3_2.sizePolicy().hasHeightForWidth())
        self.label_rev3_2.setSizePolicy(sizePolicy)
        self.label_rev3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev3_2.setObjectName("label_rev3_2")
        self.gridLayout.addWidget(self.label_rev3_2, 12, 0, 1, 1)
        self.label_l3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l3_2.setObjectName("label_l3_2")
        self.gridLayout.addWidget(self.label_l3_2, 11, 6, 1, 1)
        self.label_l2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l2.setObjectName("label_l2")
        self.gridLayout.addWidget(self.label_l2, 4, 5, 1, 1)
        self.lcdNumber_rev11_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_l3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_l3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_l3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_l3.setObjectName("lcdNumber_rev11_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l3, 8, 6, 1, 1)
        self.lineEdit_rev5_l2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_l2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_l2.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_l2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_l2.setObjectName("lineEdit_rev5_l2")
        self.gridLayout.addWidget(self.lineEdit_rev5_l2, 13, 5, 1, 1)
        self.label_rev3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev3.sizePolicy().hasHeightForWidth())
        self.label_rev3.setSizePolicy(sizePolicy)
        self.label_rev3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev3.setObjectName("label_rev3")
        self.gridLayout.addWidget(self.label_rev3, 5, 0, 1, 1)
        self.label_l3 = QtWidgets.QLabel(self.centralwidget)
        self.label_l3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l3.setObjectName("label_l3")
        self.gridLayout.addWidget(self.label_l3, 4, 6, 1, 1)
        self.label_l1 = QtWidgets.QLabel(self.centralwidget)
        self.label_l1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l1.setObjectName("label_l1")
        self.gridLayout.addWidget(self.label_l1, 4, 4, 1, 1)
        self.lcdNumber_rev3_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_l1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_l1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_l1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_l1.setObjectName("lcdNumber_rev3_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l1, 5, 4, 1, 1)
        self.plainTextEdit_reg_fallos = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_reg_fallos.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_reg_fallos.setSizePolicy(sizePolicy)
        self.plainTextEdit_reg_fallos.setObjectName("plainTextEdit_reg_fallos")
        self.gridLayout.addWidget(self.plainTextEdit_reg_fallos, 5, 7, 11, 1)
        self.lineEdit_rev3_r1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_r1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_r1.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_r1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_r1.setObjectName("lineEdit_rev3_r1")
        self.gridLayout.addWidget(self.lineEdit_rev3_r1, 12, 1, 1, 1)
        self.lcdNumber_rev8_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_l2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_l2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_l2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_l2.setObjectName("lcdNumber_rev8_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l2, 7, 5, 1, 1)
        self.lineEdit_rev8_l2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_l2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_l2.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_l2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_l2.setObjectName("lineEdit_rev8_l2")
        self.gridLayout.addWidget(self.lineEdit_rev8_l2, 14, 5, 1, 1)
        self.lcdNumber_rev11_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_l2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_l2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_l2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_l2.setObjectName("lcdNumber_rev11_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l2, 8, 5, 1, 1)
        self.lcdNumber_rev5_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_r2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_r2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_r2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_r2.setObjectName("lcdNumber_rev5_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r2, 6, 2, 1, 1)
        self.lineEdit_rev8_l3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_l3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_l3.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_l3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_l3.setObjectName("lineEdit_rev8_l3")
        self.gridLayout.addWidget(self.lineEdit_rev8_l3, 14, 6, 1, 1)
        self.lineEdit_rev8_r3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_r3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_r3.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_r3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_r3.setObjectName("lineEdit_rev8_r3")
        self.gridLayout.addWidget(self.lineEdit_rev8_r3, 14, 3, 1, 1)
        self.lineEdit_rev3_l3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_l3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_l3.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_l3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_l3.setObjectName("lineEdit_rev3_l3")
        self.gridLayout.addWidget(self.lineEdit_rev3_l3, 12, 6, 1, 1)
        self.lineEdit_rev11_r2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_r2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_r2.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_r2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_r2.setObjectName("lineEdit_rev11_r2")
        self.gridLayout.addWidget(self.lineEdit_rev11_r2, 15, 2, 1, 1)
        self.lineEdit_rev5_r3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_r3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_r3.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_r3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_r3.setObjectName("lineEdit_rev5_r3")
        self.gridLayout.addWidget(self.lineEdit_rev5_r3, 13, 3, 1, 1)
        self.lineEdit_rev11_r3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_r3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_r3.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_r3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_r3.setObjectName("lineEdit_rev11_r3")
        self.gridLayout.addWidget(self.lineEdit_rev11_r3, 15, 3, 1, 1)
        self.label_r1_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_r1_2.sizePolicy().hasHeightForWidth())
        self.label_r1_2.setSizePolicy(sizePolicy)
        self.label_r1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r1_2.setObjectName("label_r1_2")
        self.gridLayout.addWidget(self.label_r1_2, 11, 1, 1, 1)
        self.label_registro = QtWidgets.QLabel(self.centralwidget)
        self.label_registro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_registro.setObjectName("label_registro")
        self.gridLayout.addWidget(self.label_registro, 4, 7, 1, 1)
        self.label_tit = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tit.sizePolicy().hasHeightForWidth())
        self.label_tit.setSizePolicy(sizePolicy)
        self.label_tit.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_tit.setFont(font)
        self.label_tit.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_tit.setObjectName("label_tit")
        self.gridLayout.addWidget(self.label_tit, 2, 2, 1, 4)
        self.lcdNumber_rev11_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_r1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_r1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_r1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_r1.setObjectName("lcdNumber_rev11_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r1, 8, 1, 1, 1)
        self.label_r2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_r2.sizePolicy().hasHeightForWidth())
        self.label_r2.setSizePolicy(sizePolicy)
        self.label_r2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r2.setObjectName("label_r2")
        self.gridLayout.addWidget(self.label_r2, 4, 2, 1, 1)
        self.lineEdit_rev5_l1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_l1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_l1.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_l1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_l1.setObjectName("lineEdit_rev5_l1")
        self.gridLayout.addWidget(self.lineEdit_rev5_l1, 13, 4, 1, 1)
        self.lcdNumber_rev11_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_l1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_l1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_l1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_l1.setObjectName("lcdNumber_rev11_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l1, 8, 4, 1, 1)
        self.lcdNumber_rev5_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_r1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_r1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_r1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_r1.setObjectName("lcdNumber_rev5_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r1, 6, 1, 1, 1)
        self.label_rev8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev8.sizePolicy().hasHeightForWidth())
        self.label_rev8.setSizePolicy(sizePolicy)
        self.label_rev8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev8.setObjectName("label_rev8")
        self.gridLayout.addWidget(self.label_rev8, 7, 0, 1, 1)
        self.lineEdit_rev5_r1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev5_r1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev5_r1.setSizePolicy(sizePolicy)
        self.lineEdit_rev5_r1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev5_r1.setObjectName("lineEdit_rev5_r1")
        self.gridLayout.addWidget(self.lineEdit_rev5_r1, 13, 1, 1, 1)
        self.lineEdit_rev8_l1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_l1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_l1.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_l1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_l1.setObjectName("lineEdit_rev8_l1")
        self.gridLayout.addWidget(self.lineEdit_rev8_l1, 14, 4, 1, 1)
        self.lcdNumber_rev5_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_l2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_l2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_l2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_l2.setObjectName("lcdNumber_rev5_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l2, 6, 5, 1, 1)
        self.lineEdit_rev11_r1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_r1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_r1.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_r1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_r1.setObjectName("lineEdit_rev11_r1")
        self.gridLayout.addWidget(self.lineEdit_rev11_r1, 15, 1, 1, 1)
        self.lineEdit_rev11_l2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_l2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_l2.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_l2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_l2.setObjectName("lineEdit_rev11_l2")
        self.gridLayout.addWidget(self.lineEdit_rev11_l2, 15, 5, 1, 1)
        self.lineEdit_rev11_l1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_l1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_l1.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_l1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_l1.setObjectName("lineEdit_rev11_l1")
        self.gridLayout.addWidget(self.lineEdit_rev11_l1, 15, 4, 1, 1)
        self.label_rev5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev5.sizePolicy().hasHeightForWidth())
        self.label_rev5.setSizePolicy(sizePolicy)
        self.label_rev5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev5.setObjectName("label_rev5")
        self.gridLayout.addWidget(self.label_rev5, 6, 0, 1, 1)
        self.lcdNumber_rev5_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_l1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_l1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_l1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_l1.setObjectName("lcdNumber_rev5_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l1, 6, 4, 1, 1)
        self.lcdNumber_rev8_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_l1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_l1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_l1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_l1.setObjectName("lcdNumber_rev8_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l1, 7, 4, 1, 1)
        self.lineEdit_rev3_r2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_r2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_r2.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_r2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_r2.setObjectName("lineEdit_rev3_r2")
        self.gridLayout.addWidget(self.lineEdit_rev3_r2, 12, 2, 1, 1)
        self.label_rev11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rev11.sizePolicy().hasHeightForWidth())
        self.label_rev11.setSizePolicy(sizePolicy)
        self.label_rev11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev11.setObjectName("label_rev11")
        self.gridLayout.addWidget(self.label_rev11, 8, 0, 1, 1)
        self.lcdNumber_rev5_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_r3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_r3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_r3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_r3.setObjectName("lcdNumber_rev5_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r3, 6, 3, 1, 1)
        self.lcdNumber_rev8_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_l3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_l3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_l3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_l3.setObjectName("lcdNumber_rev8_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l3, 7, 6, 1, 1)
        self.lcdNumber_rev11_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_r3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_r3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_r3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_r3.setObjectName("lcdNumber_rev11_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r3, 8, 3, 1, 1)
        self.comboBox_art = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_art.sizePolicy().hasHeightForWidth())
        self.comboBox_art.setSizePolicy(sizePolicy)
        self.comboBox_art.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_art.setObjectName("comboBox_art")
        self.comboBox_art.addItem("")
        self.comboBox_art.addItem("")
        self.comboBox_art.addItem("")
        self.comboBox_art.addItem("")
        self.comboBox_art.addItem("")
        self.gridLayout.addWidget(self.comboBox_art, 10, 1, 1, 1)
        self.lcdNumber_rev5_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev5_l3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev5_l3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev5_l3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev5_l3.setObjectName("lcdNumber_rev5_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l3, 6, 6, 1, 1)
        self.lcdNumber_rev3_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_l3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_l3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_l3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_l3.setObjectName("lcdNumber_rev3_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l3, 5, 6, 1, 1)
        self.lcdNumber_rev11_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev11_r2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev11_r2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev11_r2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev11_r2.setObjectName("lcdNumber_rev11_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r2, 8, 2, 1, 1)
        self.label_tit_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tit_3.sizePolicy().hasHeightForWidth())
        self.label_tit_3.setSizePolicy(sizePolicy)
        self.label_tit_3.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_tit_3.setFont(font)
        self.label_tit_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_tit_3.setObjectName("label_tit_3")
        self.gridLayout.addWidget(self.label_tit_3, 10, 3, 1, 2)
        self.label_l1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l1_2.setObjectName("label_l1_2")
        self.gridLayout.addWidget(self.label_l1_2, 11, 4, 1, 1)
        self.label_limits = QtWidgets.QLabel(self.centralwidget)
        self.label_limits.setAlignment(QtCore.Qt.AlignCenter)
        self.label_limits.setObjectName("label_limits")
        self.gridLayout.addWidget(self.label_limits, 10, 2, 1, 1)
        self.lcdNumber_rev3_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_l2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_l2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_l2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_l2.setObjectName("lcdNumber_rev3_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l2, 5, 5, 1, 1)
        self.label_l2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l2_2.setObjectName("label_l2_2")
        self.gridLayout.addWidget(self.label_l2_2, 11, 5, 1, 1)
        self.lcdNumber_rev8_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_r1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_r1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_r1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_r1.setObjectName("lcdNumber_rev8_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r1, 7, 1, 1, 1)
        self.lcdNumber_rev3_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_r3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_r3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_r3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_r3.setObjectName("lcdNumber_rev3_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r3, 5, 3, 1, 1)
        self.lineEdit_rev3_r3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_r3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_r3.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_r3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_r3.setObjectName("lineEdit_rev3_r3")
        self.gridLayout.addWidget(self.lineEdit_rev3_r3, 12, 3, 1, 1)
        self.lcdNumber_rev3_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_r1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_r1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_r1.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_r1.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_r1.setObjectName("lcdNumber_rev3_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r1, 5, 1, 1, 1)
        self.lineEdit_rev8_r2 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_r2.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_r2.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_r2.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_r2.setObjectName("lineEdit_rev8_r2")
        self.gridLayout.addWidget(self.lineEdit_rev8_r2, 14, 2, 1, 1)
        self.lineEdit_rev11_l3 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev11_l3.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev11_l3.setSizePolicy(sizePolicy)
        self.lineEdit_rev11_l3.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev11_l3.setObjectName("lineEdit_rev11_l3")
        self.gridLayout.addWidget(self.lineEdit_rev11_l3, 15, 6, 1, 1)
        self.label_r3 = QtWidgets.QLabel(self.centralwidget)
        self.label_r3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r3.setObjectName("label_r3")
        self.gridLayout.addWidget(self.label_r3, 4, 3, 1, 1)
        self.lineEdit_rev3_l1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev3_l1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev3_l1.setSizePolicy(sizePolicy)
        self.lineEdit_rev3_l1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev3_l1.setObjectName("lineEdit_rev3_l1")
        self.gridLayout.addWidget(self.lineEdit_rev3_l1, 12, 4, 1, 1)
        self.lcdNumber_rev8_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_r3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_r3.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_r3.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_r3.setObjectName("lcdNumber_rev8_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r3, 7, 3, 1, 1)
        self.lineEdit_rev8_r1 = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev8_r1.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev8_r1.setSizePolicy(sizePolicy)
        self.lineEdit_rev8_r1.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_rev8_r1.setObjectName("lineEdit_rev8_r1")
        self.gridLayout.addWidget(self.lineEdit_rev8_r1, 14, 1, 1, 1)
        self.label_r2_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_r2_2.sizePolicy().hasHeightForWidth())
        self.label_r2_2.setSizePolicy(sizePolicy)
        self.label_r2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r2_2.setObjectName("label_r2_2")
        self.gridLayout.addWidget(self.label_r2_2, 11, 2, 1, 1)
        self.lcdNumber_rev8_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev8_r2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev8_r2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev8_r2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev8_r2.setObjectName("lcdNumber_rev8_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r2, 7, 2, 1, 1)
        self.label_r3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_r3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r3_2.setObjectName("label_r3_2")
        self.gridLayout.addWidget(self.label_r3_2, 11, 3, 1, 1)
        self.lcdNumber_rev3_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_rev3_r2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_rev3_r2.setSizePolicy(sizePolicy)
        self.lcdNumber_rev3_r2.setMinimumSize(QtCore.QSize(150, 40))
        self.lcdNumber_rev3_r2.setObjectName("lcdNumber_rev3_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r2, 5, 2, 1, 1)
        self.label_r1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_r1.sizePolicy().hasHeightForWidth())
        self.label_r1.setSizePolicy(sizePolicy)
        self.label_r1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r1.setObjectName("label_r1")
        self.gridLayout.addWidget(self.label_r1, 4, 1, 1, 1)
        self.comboBox_canal = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_canal.sizePolicy().hasHeightForWidth())
        self.comboBox_canal.setSizePolicy(sizePolicy)
        self.comboBox_canal.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_canal.setObjectName("comboBox_canal")
        self.comboBox_canal.addItem("")
        self.comboBox_canal.addItem("")
        self.comboBox_canal.addItem("")
        self.comboBox_canal.addItem("")
        self.gridLayout.addWidget(self.comboBox_canal, 2, 1, 1, 1)
        self.pushButton_en_pie = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_en_pie.sizePolicy().hasHeightForWidth())
        self.pushButton_en_pie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_en_pie.setFont(font)
        self.pushButton_en_pie.setObjectName("pushButton_en_pie")
        self.gridLayout.addWidget(self.pushButton_en_pie, 0, 3, 1, 2)
        self.comboBox_fallos = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_fallos.sizePolicy().hasHeightForWidth())
        self.comboBox_fallos.setSizePolicy(sizePolicy)
        self.comboBox_fallos.setObjectName("comboBox_fallos")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.comboBox_fallos.addItem("")
        self.gridLayout.addWidget(self.comboBox_fallos, 10, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 6)
        self.label_cod_fallos = QtWidgets.QLabel(self.centralwidget)
        self.label_cod_fallos.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cod_fallos.setObjectName("label_cod_fallos")
        self.gridLayout.addWidget(self.label_cod_fallos, 10, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robominer GUI"))
        self.label_rev8_2.setText(_translate("MainWindow", "Rev8"))
        self.label_rev11_2.setText(_translate("MainWindow", "Rev11"))
        self.label_rev5_2.setText(_translate("MainWindow", "Rev5"))
        self.label_rev3_2.setText(_translate("MainWindow", "Rev3"))
        self.label_l3_2.setText(_translate("MainWindow", "Pata l3"))
        self.label_l2.setText(_translate("MainWindow", "Pata l2"))
        self.label_rev3.setText(_translate("MainWindow", "Rev3"))
        self.label_l3.setText(_translate("MainWindow", "Pata l3"))
        self.label_l1.setText(_translate("MainWindow", "Pata l1"))
        self.label_r1_2.setText(_translate("MainWindow", "Pata r1"))
        self.label_registro.setText(_translate("MainWindow", "Registro de fallos"))
        self.label_tit.setText(_translate("MainWindow", "Ángulo de cada articulación (º)"))
        self.label_r2.setText(_translate("MainWindow", "Pata r2"))
        self.label_rev8.setText(_translate("MainWindow", "Rev8"))
        self.label_rev5.setText(_translate("MainWindow", "Rev5"))
        self.label_rev11.setText(_translate("MainWindow", "Rev11"))
        self.comboBox_art.setItemText(0, _translate("MainWindow", "Elija articulación"))
        self.comboBox_art.setItemText(1, _translate("MainWindow", "Rev3"))
        self.comboBox_art.setItemText(2, _translate("MainWindow", "Rev5"))
        self.comboBox_art.setItemText(3, _translate("MainWindow", "Rev8"))
        self.comboBox_art.setItemText(4, _translate("MainWindow", "Rev11"))
        self.label_tit_3.setText(_translate("MainWindow", "Nuevas posiciones y fallos"))
        self.label_l1_2.setText(_translate("MainWindow", "Pata l1"))
        self.label_limits.setText(_translate("MainWindow", "Rango:"))
        self.label_l2_2.setText(_translate("MainWindow", "Pata l2"))
        self.label_r3.setText(_translate("MainWindow", "Pata r3"))
        self.label_r2_2.setText(_translate("MainWindow", "Pata r2"))
        self.label_r3_2.setText(_translate("MainWindow", "Pata r3"))
        self.label_r1.setText(_translate("MainWindow", "Pata r1"))
        self.comboBox_canal.setItemText(0, _translate("MainWindow", "Seleccione canal"))
        self.comboBox_canal.setItemText(1, _translate("MainWindow", "Ángulo"))
        self.comboBox_canal.setItemText(2, _translate("MainWindow", "Velocidad angular"))
        self.comboBox_canal.setItemText(3, _translate("MainWindow", "Par"))
        self.pushButton_en_pie.setText(_translate("MainWindow", "Iniciar movimiento"))
        self.comboBox_fallos.setItemText(0, _translate("MainWindow", "Seleccione fallo"))
        self.comboBox_fallos.setItemText(1, _translate("MainWindow", "Motor inhab."))
        self.comboBox_fallos.setItemText(2, _translate("MainWindow", "Motor débil"))
        self.comboBox_fallos.setItemText(3, _translate("MainWindow", "Desanclar art."))
        self.comboBox_fallos.setItemText(4, _translate("MainWindow", "Motor bloqueado"))
        self.comboBox_fallos.setItemText(5, _translate("MainWindow", "Motor desviado"))
        self.comboBox_fallos.setItemText(6, _translate("MainWindow", "Sensor valor nulo"))
        self.comboBox_fallos.setItemText(7, _translate("MainWindow", "Sensor valor fijo"))
        self.comboBox_fallos.setItemText(8, _translate("MainWindow", "Sensor error fijo"))
        self.comboBox_fallos.setItemText(9, _translate("MainWindow", "Sensor error prop."))
        self.label_cod_fallos.setText(_translate("MainWindow", "Código: "))

