# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pos_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 777)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_en_pie = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_en_pie.setObjectName("pushButton_en_pie")
        self.gridLayout.addWidget(self.pushButton_en_pie, 0, 0, 1, 7)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 7)
        self.label_r1 = QtWidgets.QLabel(self.centralwidget)
        self.label_r1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r1.setObjectName("label_r1")
        self.gridLayout.addWidget(self.label_r1, 2, 1, 1, 1)
        self.label_r2 = QtWidgets.QLabel(self.centralwidget)
        self.label_r2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r2.setObjectName("label_r2")
        self.gridLayout.addWidget(self.label_r2, 2, 2, 1, 1)
        self.label_r3 = QtWidgets.QLabel(self.centralwidget)
        self.label_r3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r3.setObjectName("label_r3")
        self.gridLayout.addWidget(self.label_r3, 2, 3, 1, 1)
        self.label_l1 = QtWidgets.QLabel(self.centralwidget)
        self.label_l1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l1.setObjectName("label_l1")
        self.gridLayout.addWidget(self.label_l1, 2, 4, 1, 1)
        self.label_l2 = QtWidgets.QLabel(self.centralwidget)
        self.label_l2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l2.setObjectName("label_l2")
        self.gridLayout.addWidget(self.label_l2, 2, 5, 1, 1)
        self.label_l3 = QtWidgets.QLabel(self.centralwidget)
        self.label_l3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_l3.setObjectName("label_l3")
        self.gridLayout.addWidget(self.label_l3, 2, 6, 1, 1)
        self.label_rev3 = QtWidgets.QLabel(self.centralwidget)
        self.label_rev3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev3.setObjectName("label_rev3")
        self.gridLayout.addWidget(self.label_rev3, 3, 0, 1, 1)
        self.lcdNumber_rev3_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_r1.setObjectName("lcdNumber_rev3_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r1, 3, 1, 1, 1)
        self.lcdNumber_rev3_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_r2.setObjectName("lcdNumber_rev3_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r2, 3, 2, 1, 1)
        self.lcdNumber_rev3_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_r3.setObjectName("lcdNumber_rev3_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev3_r3, 3, 3, 1, 1)
        self.lcdNumber_rev3_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_l1.setObjectName("lcdNumber_rev3_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l1, 3, 4, 1, 1)
        self.lcdNumber_rev3_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_l2.setObjectName("lcdNumber_rev3_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l2, 3, 5, 1, 1)
        self.lcdNumber_rev3_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev3_l3.setObjectName("lcdNumber_rev3_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev3_l3, 3, 6, 1, 1)
        self.label_rev5 = QtWidgets.QLabel(self.centralwidget)
        self.label_rev5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev5.setObjectName("label_rev5")
        self.gridLayout.addWidget(self.label_rev5, 4, 0, 1, 1)
        self.lcdNumber_rev5_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_r1.setObjectName("lcdNumber_rev5_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r1, 4, 1, 1, 1)
        self.lcdNumber_rev5_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_r2.setObjectName("lcdNumber_rev5_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r2, 4, 2, 1, 1)
        self.lcdNumber_rev5_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_r3.setObjectName("lcdNumber_rev5_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev5_r3, 4, 3, 1, 1)
        self.lcdNumber_rev5_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_l1.setObjectName("lcdNumber_rev5_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l1, 4, 4, 1, 1)
        self.lcdNumber_rev5_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_l2.setObjectName("lcdNumber_rev5_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l2, 4, 5, 1, 1)
        self.lcdNumber_rev5_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev5_l3.setObjectName("lcdNumber_rev5_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev5_l3, 4, 6, 1, 1)
        self.label_rev8 = QtWidgets.QLabel(self.centralwidget)
        self.label_rev8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev8.setObjectName("label_rev8")
        self.gridLayout.addWidget(self.label_rev8, 5, 0, 1, 1)
        self.lcdNumber_rev8_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_r1.setObjectName("lcdNumber_rev8_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r1, 5, 1, 1, 1)
        self.lcdNumber_rev8_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_r2.setObjectName("lcdNumber_rev8_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r2, 5, 2, 1, 1)
        self.lcdNumber_rev8_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_r3.setObjectName("lcdNumber_rev8_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev8_r3, 5, 3, 1, 1)
        self.lcdNumber_rev8_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_l1.setObjectName("lcdNumber_rev8_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l1, 5, 4, 1, 1)
        self.lcdNumber_rev8_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_l2.setObjectName("lcdNumber_rev8_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l2, 5, 5, 1, 1)
        self.lcdNumber_rev8_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev8_l3.setObjectName("lcdNumber_rev8_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev8_l3, 5, 6, 1, 1)
        self.label_rev11 = QtWidgets.QLabel(self.centralwidget)
        self.label_rev11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rev11.setObjectName("label_rev11")
        self.gridLayout.addWidget(self.label_rev11, 6, 0, 1, 1)
        self.lcdNumber_rev11_r1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_r1.setObjectName("lcdNumber_rev11_r1")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r1, 6, 1, 1, 1)
        self.lcdNumber_rev11_r2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_r2.setObjectName("lcdNumber_rev11_r2")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r2, 6, 2, 1, 1)
        self.lcdNumber_rev11_r3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_r3.setObjectName("lcdNumber_rev11_r3")
        self.gridLayout.addWidget(self.lcdNumber_rev11_r3, 6, 3, 1, 1)
        self.lcdNumber_rev11_l1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_l1.setObjectName("lcdNumber_rev11_l1")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l1, 6, 4, 1, 1)
        self.lcdNumber_rev11_l2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_l2.setObjectName("lcdNumber_rev11_l2")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l2, 6, 5, 1, 1)
        self.lcdNumber_rev11_l3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rev11_l3.setObjectName("lcdNumber_rev11_l3")
        self.gridLayout.addWidget(self.lcdNumber_rev11_l3, 6, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        #self.pushButton_en_pie.clicked.connect(MainWindow.en_pie_slot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Position GUI"))
        self.pushButton_en_pie.setText(_translate("MainWindow", "En pie!"))
        self.label.setText(_translate("MainWindow", "Ángulo de cada articulación en grados"))
        self.label_r1.setText(_translate("MainWindow", "Pata r1"))
        self.label_r2.setText(_translate("MainWindow", "Pata r2"))
        self.label_r3.setText(_translate("MainWindow", "Pata r3"))
        self.label_l1.setText(_translate("MainWindow", "Pata l1"))
        self.label_l2.setText(_translate("MainWindow", "Pata l2"))
        self.label_l3.setText(_translate("MainWindow", "Pata l3"))
        self.label_rev3.setText(_translate("MainWindow", "Rev3"))
        self.label_rev5.setText(_translate("MainWindow", "Rev5"))
        self.label_rev8.setText(_translate("MainWindow", "Rev8"))
        self.label_rev11.setText(_translate("MainWindow", "Rev11"))

